import { ERRORS_TRANSLATION_PREFIX } from '../constants/translation-prefixes.constant';

export enum ValidatorsKeys {
  Required = 'required',
  Email = 'email',
  Minlength = 'minlength',
  Maxlength = 'maxlength',
  Password = 'password',
  PasswordMismatch = 'password mismatch',
  Max = 'max',
  Min = 'min',
  NotEquivalent = 'notEquivalent',
  Integer = 'integer',
  Pattern = 'pattern',
  ForbiddenSymbols = 'forbiddenSymbols',
  LessThanNumber = 'lessThanNumber',
  PhoneNumber = 'phoneNumber',
  ExistingUserName = 'existingUserName',
  BadWords = 'badWords',
  WithoutSpace = 'withoutSpace',
  AtLeastOneNumber = 'atLeastOneNumber',
  AtLeastOneUpperCaseAndOneLowerCaseLetter = 'atLeastOneUpperCaseAndOneLowerCaseLetter',
  UniqueStaticPageUrl = 'uniqueStaticPageUrl',
  LatinLettersNumbersHyphen = 'latinLettersNumbersHyphen',
  NumbersDotsHyphen = 'NumbersDotsHyphen',
  CompareFromWithTo = 'compareFromWithTo',
  CompareToWithFrom = 'compareToWithFrom',
  LessThanMax24H = 'lessThanMax24h',
  CompareDateToWithFrom = 'compareDateToWithFrom',
  CompareDateFromWithTo = 'compareDateFromWithTo',
  PasswordDoesNotMatchRequirements = 'Password does not match requirements',
  MaxDaysLimitExceeded = 'maxDaysLimitExceeded',
  InvalidRange = 'invalidRange',
}

export const VALIDATION_MESSAGES: Record<ValidatorsKeys, string> = {
  [ValidatorsKeys.Required]: ERRORS_TRANSLATION_PREFIX + 'This field is required',
  [ValidatorsKeys.Email]: ERRORS_TRANSLATION_PREFIX + 'Incorrect Email',
  [ValidatorsKeys.Password]: ERRORS_TRANSLATION_PREFIX + 'Password should contain',
  [ValidatorsKeys.Minlength]: ERRORS_TRANSLATION_PREFIX + 'Should be minimum symbols',
  [ValidatorsKeys.Maxlength]: ERRORS_TRANSLATION_PREFIX + 'Should be maximum symbols',
  [ValidatorsKeys.PasswordMismatch]: ERRORS_TRANSLATION_PREFIX + 'Passwords not equal',
  [ValidatorsKeys.Max]: ERRORS_TRANSLATION_PREFIX + 'Max Validator',
  [ValidatorsKeys.Min]: ERRORS_TRANSLATION_PREFIX + 'Min Validator',
  [ValidatorsKeys.NotEquivalent]: ERRORS_TRANSLATION_PREFIX + 'Passwords must match',
  [ValidatorsKeys.Integer]: ERRORS_TRANSLATION_PREFIX + 'Only integers are allowed',
  [ValidatorsKeys.Pattern]: ERRORS_TRANSLATION_PREFIX + 'Invalid pattern',
  [ValidatorsKeys.ForbiddenSymbols]: ERRORS_TRANSLATION_PREFIX + 'Special characters and spaces are not allowed',
  [ValidatorsKeys.LessThanNumber]: 'Min > Max',
  [ValidatorsKeys.ExistingUserName]: ERRORS_TRANSLATION_PREFIX + 'existingUserName',
  [ValidatorsKeys.BadWords]: ERRORS_TRANSLATION_PREFIX + 'badWords',
  [ValidatorsKeys.PhoneNumber]: ERRORS_TRANSLATION_PREFIX + 'IncorrectPhoneNumber',
  [ValidatorsKeys.WithoutSpace]: ERRORS_TRANSLATION_PREFIX + 'WithoutSpace',
  [ValidatorsKeys.AtLeastOneNumber]: ERRORS_TRANSLATION_PREFIX + 'AtLeastOneNumber',
  [ValidatorsKeys.AtLeastOneUpperCaseAndOneLowerCaseLetter]: ERRORS_TRANSLATION_PREFIX + 'AtLeastOneUpperCaseAndOneLowerCaseLetter',
  [ValidatorsKeys.UniqueStaticPageUrl]: ERRORS_TRANSLATION_PREFIX + 'URL must be unique',
  [ValidatorsKeys.LatinLettersNumbersHyphen]: ERRORS_TRANSLATION_PREFIX + 'OnlyLatinLettersNumbersDashesAvailable',
  [ValidatorsKeys.NumbersDotsHyphen]: ERRORS_TRANSLATION_PREFIX + 'Only numbers, dots and hyphens are allowed',
  [ValidatorsKeys.LessThanMax24H]: ERRORS_TRANSLATION_PREFIX + 'Min > Max(24h)',
  [ValidatorsKeys.CompareFromWithTo]: ERRORS_TRANSLATION_PREFIX + 'CompareFromWithTo',
  [ValidatorsKeys.CompareToWithFrom]: ERRORS_TRANSLATION_PREFIX + 'CompareToWithFrom',
  [ValidatorsKeys.CompareDateFromWithTo]: ERRORS_TRANSLATION_PREFIX + 'compareDateFromWithTo',
  [ValidatorsKeys.CompareDateToWithFrom]: ERRORS_TRANSLATION_PREFIX + 'compareDateToWithFrom',
  [ValidatorsKeys.PasswordDoesNotMatchRequirements]: ERRORS_TRANSLATION_PREFIX + 'Password does not match requirements',
  [ValidatorsKeys.MaxDaysLimitExceeded]: ERRORS_TRANSLATION_PREFIX + 'MaxDaysLimitExceeded',
  [ValidatorsKeys.InvalidRange]: ERRORS_TRANSLATION_PREFIX + 'Invalid range',
};
